public class OpportunityTriggerHandler extends TriggerHandler {

    public OpportunityTriggerHandler() {
        this.setMaxLoopCount(1);
    }
  
  public override void beforeInsert() {
     // OpportunityHelper.firstMethod();
     // OpportunityHelper.secondMethod();
     // OpportunityHelper.thirdMethod();
     // OpportunityHelper.fourthMethod();
  }
  
  public override void afterInsert() {
    
  }
  
  public override void beforeUpdate() {
    
  }
  
  public override void afterUpdate() {
    
  }

}